# Generated by Django 4.2.4 on 2023-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="password",
            field=models.CharField(),
        ),
    ]
