# Generated by Django 4.2.4 on 2023-08-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taskapp", "0003_userdetails_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.CharField(primary_key=True, serialize=False)),
                ("amount", models.SmallIntegerField()),
                ("tenure_month", models.SmallIntegerField()),
                ("status", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
